version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: proyectos_db
    environment:
      POSTGRES_DB: proyectos_glocation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: proyectos_backend
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/proyectos_glocation
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres

frontend:
  build: ./frontend
  ports:
    - "5173:5173"
  depends_on:
    - backend
    
volumes:
  postgres_data: